"""followers

Revision ID: 597708757525
Revises: 2b1161b86770
Create Date: 2018-11-21 22:01:48.824909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597708757525'
down_revision = '2b1161b86770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
